### ISSUE TITLE
wotw tree icon

### ISSUE THREAD

**Issue by toadettexmushina** [ori-rando/assets#2]
![treewotw](https://user-images.githubusercontent.com/23561609/162598226-21b4491a-59d2-4175-973d-73d5cb903b05.png)

wotw tree map icon - could use for tracker?

**Comment by MunWolf** [comment]
Looks good to me, @timoschwarzer thoughts?

**Comment by toadettexmushina** [comment]
![treewotw](https://user-images.githubusercontent.com/23561609/162632097-b84079cf-eefd-42bf-a6a6-c34e38854a6d.png)
symmetrical version

**Comment by timoschwarzer** [comment]
Sure, if possible, you can make a PR against ori-rando/ui and replace this file: https://github.com/ori-rando/ui/blob/main/assets/images/tracker/tree.png
