### ISSUE TITLE
New Icons!

### ISSUE THREAD

**Issue by toadettexmushina** [ori-rando/assets#3]
I can't be bothered to figure out a pull request rn
![extrashuriken](https://github.com/ori-community/wotw-rando-assets/assets/23561609/03cd17e0-92fc-40e4-8a2f-61528d54b709)
![rapidsentry](https://github.com/ori-community/wotw-rando-assets/assets/23561609/6015900d-19f9-48e7-9a2d-a24009176dfa)
![sentrybarrage](https://github.com/ori-community/wotw-rando-assets/assets/23561609/7ab348dd-8481-49ee-b61f-c80fe2776960)

**Comment by toadettexmushina** [comment]
![powerflap](https://github.com/ori-community/wotw-rando-assets/assets/23561609/698ff97f-4dda-42ea-bb76-201d1689fb08)

**Comment by toadettexmushina** [comment]
![powerflap](https://github.com/ori-community/wotw-rando-assets/assets/23561609/7e63e385-2ded-49d2-bf10-7b0361a8be0b)

**Comment by toadettexmushina** [comment]
![shopmap](https://github.com/ori-community/wotw-rando-assets/assets/23561609/1779f9f2-62ef-4168-ba03-a82a215addbf)

**Comment by toadettexmushina** [comment]
![ultraflap](https://github.com/ori-community/wotw-rando-assets/assets/23561609/f5a889c1-82d1-422f-975c-ba27d48c38b2)

**Comment by timoschwarzer** [comment]
very late but thank you! ❤️
